# Generated by Django 5.0 on 2025-11-21 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('midname', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('bday', models.DateField(max_length=30)),
                ('group', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.students')),
                ('grade_first', models.IntegerField()),
                ('grade_third', models.IntegerField()),
                ('grade_fourth', models.IntegerField()),
                ('grade_second', models.IntegerField()),
                ('result', models.FloatField(editable=False)),
            ],
        ),
    ]
