# Generated by Django 5.0 on 2025-11-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_exams_result_alter_students_bday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='bday',
            field=models.CharField(max_length=10),
        ),
    ]
